server:
  port: 8080

spring:
  application:
    name: exception-catch
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exception_catch?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456